"""
config.py - Configuration settings for fall detection system
"""

# ================= PATHS =================
MODEL_PATH_DETECTION = "yolov8s.pt"
MODEL_PATH_POSE = "yolov8s-pose.pt"
INPUT_DIR = "/content/drive/MyDrive/orbro/Fall_vid"
OUTPUT_DIR = "/content/drive/MyDrive/orbro/Fall_vid_output"

# ================= DETECTION THRESHOLDS =================
CONF_THRESH = 0.4
POSE_CONF_THRESH = 0.5
MIN_AREA_RATIO = 0.002
MAX_MISSING = 20
MIN_KEYPOINTS_VISIBLE = 5

# ================= MOTION THRESHOLDS =================
STATIC_MOVE_THRESH = 3
MIN_LIVING_FRAMES = 20
MANNEQUIN_MOTION_THRESH = 0.5
MANNEQUIN_CHECK_FRAMES = 30
MANNEQUIN_JITTER_THRESH = 1.0

# ================= FALL DETECTION THRESHOLDS =================
STANDING_CONFIDENCE_THRESH = 0.85
FALLING_CONFIDENCE_THRESH = 0.70
FALLEN_CONFIDENCE_THRESH = 0.60
MIN_FALL_CONFIDENCE = 0.60

HEIGHT_DROP_RATIO = 0.30
ASPECT_RATIO_CHANGE = 1.5
VEL_Y_THRESH = 20
ACC_Y_THRESH = 15
BODY_ANGLE_THRESH = 50
POST_FALL_STATIC_FRAMES = 30
FALL_CONFIRM_FRAMES = 3

# ================= OCCLUSION & BODY PART TRACKING =================
OCCLUSION_AREA_RATIO = 0.5
OCCLUSION_KEYPOINT_RATIO = 0.4
SUDDEN_DISAPPEAR_FRAMES = 5
REAPPEAR_GROUND_THRESH = 0.3
BODY_PART_MATCH_THRESH = 50
MIN_BODY_PART_MOVEMENT = 2.0

# ================= VISUALIZATION =================
COLOR_STANDING = (0, 255, 0)
COLOR_FALLING = (0, 165, 255)
COLOR_FALLEN = (0, 0, 255)
COLOR_KEYPOINT = (255, 255, 0)
COLOR_BODY_PART = (255, 0, 255)
COLOR_MANNEQUIN = (128, 128, 128)
